/*
	그룹별 조건에 맞는 식당 목록 출력하기
	https://school.programmers.co.kr/learn/courses/30/lessons/131124
*/

WITH A AS (
	SELECT R.MEMBER_ID, COUNT(*) AS CNT
	FROM REST_REVIEW AS R
	GROUP BY MEMBER_ID
	ORDER BY CNT DESC
	LIMIT 1
)

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM A
RIGHT JOIN REST_REVIEW AS R ON R.MEMBER_ID = A.MEMBER_ID
JOIN MEMBER_PROFILE AS M ON A.MEMBER_ID = M.MEMBER_ID
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;