/*
	년, 월, 성별 별 상품 구매 회원 수 구하기
	https://school.programmers.co.kr/learn/courses/30/lessons/131532
*/

SELECT 
    YEAR(SALES_DATE)AS YEAR
    ,MONTH(SALES_DATE)AS MONTH
    ,GENDER
    ,COUNT(DISTINCT(ONLINE.USER_ID))AS USERS
FROM ONLINE_SALE AS ONLINE
LEFT JOIN USER_INFO AS USER
ON ONLINE.USER_ID= USER.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR,MONTH,GENDER
ORDER BY YEAR,MONTH,GENDER