/*
	상품을 구매한 회원 비율 구하기
	https://school.programmers.co.kr/learn/courses/30/lessons/131534
*/

WITH J2021 as (
	SELECT COUNT(USER_ID) as JOINED_USERS
	FROM USER_INFO
	WHERE YEAR(JOINED) = 2021
	)

SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTh,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USER,
    ROUND(COUNT(DISTINCT USER_ID) / J2021.JOINED_USERS, 1) AS PURCHASED_RATIO
FROM ONLINE_SALE, J2021
WHERE USER_ID IN (
					SELECT USER_ID
                 	FROM USER_INFO
                 	WHERE YEAR(JOINED) = 2021)
GROUP BY 1, 2
ORDER BY 1, 2