/*
	상품 별 오프라인 매출 구하기
	https://school.programmers.co.kr/learn/courses/30/lessons/131533
*/

SELECT T1.PRODUCT_CODE , (T2.COUNT * T1.PRICE) AS 'SALES'
FROM PRODUCT T1 JOIN 
     (SELECT SUM(SALES_AMOUNT) AS 'COUNT',OFFLINE_SALE_ID,PRODUCT_ID,SALES_AMOUNT,SALES_DATE FROM OFFLINE_SALE GROUP BY PRODUCT_ID) T2 
     ON T1.PRODUCT_ID = T2.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC