/*
	성분으로 구분한 아이스크림 총 주문량
	https://school.programmers.co.kr/learn/courses/30/lessons/133026
*/

SELECT A.INGREDIENT_TYPE, SUM(B.TOTAL_ORDER) AS TOTAL_ORDER
FROM ICECREAM_INFO A
JOIN FIRST_HALF B ON A.FLAVOR = B.FLAVOR
GROUP BY A.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC
