/*
	오랜 기간 보호한 동물(1)
	https://school.programmers.co.kr/learn/courses/30/lessons/59044
*/

SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS AS A
LEFT JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.DATETIME IS NULL
ORDER BY A.DATETIME ASC
LIMIT 3;