/*
	오프라인/온라인 판매 데이터 통합하기
	https://school.programmers.co.kr/learn/courses/30/lessons/131537
*/

SELECT DATE_FORMAT(UN.SALES_DATE, "%Y-%m-%d") AS SALES_DATE, UN.PRODUCT_ID, UN.USER_ID, UN.SALES_AMOUNT
FROM (
	(
		SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
		FROM ONLINE_SALE
		WHERE YEAR(SALES_DATE) = 2022
		AND MONTH(SALES_DATE) = 3
	)
	UNION ALL
	(
		SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
		FROM OFFLINE_SALE
		WHERE YEAR(SALES_DATE) = 2022
		AND MONTH(SALES_DATE) = 3
	)
) UN /* Oracle에서는 이렇게 ALIAS를 줄 필요가 없지만, Mysql은 ALIAS를 주지 않으면 무조건 에러(Every derived table must have its own alias) */
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;
