/*
	주문량이 많은 아이스크림들 조회하기
	https://school.programmers.co.kr/learn/courses/30/lessons/133027
*/

SELECT F.FLAVOR
FROM FIRST_HALF AS F
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
FROM JULY
GROUP BY FLAVOR) J
ON F.FLAVOR= J.FLAVOR 
ORDER BY J.TOTAL+ F.TOTAL_ORDER DESC
LIMIT 3;
